// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXRi-qfrzIMP28ak4j1dU6HxH-1A0Y2EM',
    appId: '1:252986816093:web:5943dbeb26af8dc9627fb4',
    messagingSenderId: '252986816093',
    projectId: 'fir-crud-4e476',
    authDomain: 'fir-crud-4e476.firebaseapp.com',
    storageBucket: 'fir-crud-4e476.appspot.com',
    measurementId: 'G-9M9KTE1CCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Zgop5lb0_xSn13Na32rvpzM893C9ZwY',
    appId: '1:252986816093:android:9d6a8bbc2aaaeee6627fb4',
    messagingSenderId: '252986816093',
    projectId: 'fir-crud-4e476',
    storageBucket: 'fir-crud-4e476.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNUjibyiNDvbi-r4AVrYW7X_Hu-o-qRc0',
    appId: '1:252986816093:ios:d608d53392e46d11627fb4',
    messagingSenderId: '252986816093',
    projectId: 'fir-crud-4e476',
    storageBucket: 'fir-crud-4e476.appspot.com',
    iosClientId: '252986816093-7js46v8pmunbufnhjsufvsmk4mu7tbvt.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopappMultiplatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNUjibyiNDvbi-r4AVrYW7X_Hu-o-qRc0',
    appId: '1:252986816093:ios:d608d53392e46d11627fb4',
    messagingSenderId: '252986816093',
    projectId: 'fir-crud-4e476',
    storageBucket: 'fir-crud-4e476.appspot.com',
    iosClientId: '252986816093-7js46v8pmunbufnhjsufvsmk4mu7tbvt.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopappMultiplatform',
  );
}
